### ISSUE TITLE
Wonky parallel solutions on SPGrids with few elements

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-hdd#10]
Absolute error norms are much larger than in serial computations, and there's a very noticeable qualitative difference in the solution's visualization.

**Comment by ftalbrecht** [comment]
e.g., the `ESV2007` testcase with `initial_refinements = 1` and `refineStepsForHalf = 1` (yielding an initial grid of 64 elements)

**Comment by renemilk** [comment]
Closing as wontfix
